// Generated by ts-to-zod
import { z } from "zod";

export const deviantArtAuthSchema = z.object({
  access_token: z.string(),
  token_type: z.string(),
  expires_in: z.number(),
  status: z.string(),
});

export const parsedURLSchema = z.object({
  title: z.string().optional().nullable(),
  user: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
});

export const deviantArtDataSchema = z.object({
  text: z.string(),
});

export const deviantArtPlaceboSchema = z.object({
  status: z.string(),
});
