// Generated by ts-to-zod
import { z } from "zod";

export const deviantArtStashSchema = z.object({
  title: z.string(),
  path: z.string().optional(),
  size: z.number().optional(),
  description: z.string().nullable(),
  parentid: z.number().optional(),
  thumb: z
    .object({
      src: z.string(),
      height: z.number(),
      width: z.number(),
      transparency: z.boolean(),
    })
    .optional(),
  artist_comments: z.string(),
  original_url: z.string(),
  category: z.string(),
  creation_time: z.number().optional(),
  files: z
    .object({
      src: z.string(),
      height: z.number(),
      width: z.number(),
      transparency: z.boolean(),
    })
    .optional(),
  submission: z
    .object({
      file_size: z.string().optional(),
      resolution: z.string().optional(),
      submitted_with: z
        .object({
          app: z.string().optional(),
          url: z.string(),
        })
        .optional(),
    })
    .optional(),
  stats: z
    .object({
      views: z.number().optional(),
      views_today: z.number().optional(),
      downloads: z.number().optional(),
      downloads_today: z.number().optional(),
    })
    .optional(),
  camera: z.record(z.string()).optional(),
  stackid: z.number(),
  itemid: z.number().optional(),
  tags: z.array(z.string()).optional(),
});

export const deviantArtStashItemSchema = z.object({
  itemid: z.number(),
  stackid: z.number(),
  title: z.string(),
  path: z.string().optional(),
  description: z.string().nullable(),
  parentid: z.number().optional(),
  artist_comments: z.string().optional(),
  tags: z.array(z.string()).optional(),
  original_url: z.string().optional(),
  category: z.string().optional(),
  creation_time: z.number().optional(),
  files: z.array(
    z.object({
      src: z.string(),
      height: z.number(),
      width: z.number(),
      transparency: z.boolean(),
    }),
  ),
  submission: z
    .object({
      file_size: z.string().optional(),
      resolution: z.string().optional(),
      submitted_with: z
        .object({
          app: z.string().optional(),
          url: z.string().optional(),
        })
        .optional(),
    })
    .optional(),
  stats: z
    .object({
      views: z.number().optional(),
      views_today: z.number().optional(),
      downloads: z.number().optional(),
      downloads_today: z.number().optional(),
    })
    .optional(),
  camera: z.record(z.string()).optional(),
  html: z.string().optional(),
  css: z.string().optional(),
  css_fonts: z.array(z.string()).optional(),
});
